language: java
jdk:
- openjdk8
sudo: false
env:
  global:
  - secure: AIBi/yDIwnImwl/wN43Qxpi5W9KdyC6dgrWGDW2BVNAssnKXKVUX1LlALcESAipQVdBAuXKNRKGwgUZSs5k5o5S5gAznaVZV2U2U7jJ+ON7+xhjdJ50qGglwUJaRiKqOiFnka7Ms/yo5LsBmhpvGoZxsLkigaK/0JL7eARWtY+U=
  - secure: NYWRJ5gw4x+wR2FiHdRZpu9zChKDK5r82G+xa015wC81Ht2Me+3roYAWZiZwnuBycqFnxzwLaCBRA1ofMW8etranMSoH2LvzIzZHHPA4/R4pbMwGvVIf7ZhuBaTb0TSgOtJmShzyO+T0aJFrOANvhTrBC1spHkhDbeiSy2CzCKI=
before_install:
  - echo "<settings><servers><server><id>sonatype-nexus-snapshots</id><username>\${env.CI_DEPLOY_USERNAME}</username><password>\${env.CI_DEPLOY_PASSWORD}</password></server></servers></settings>" > ~/settings.xml
script:
  - "if [ ${TRAVIS_PULL_REQUEST} = 'false' ]; then mvn clean deploy --settings ~/settings.xml; else mvn clean verify; fi"
